1.1.0
* NEW: argument parsing for all scripts.
* NEW: help info in all scripts.
* NEW: add '-r <remote>' option to jgpush.
* NEW: remove deprecated commands in deploy.bat.
* DEPRECATE: jgpush, jgstash.
* DEPRECATE: replace jggrepcommit with jggrep*a*commit.
* README: add amend last commit.
* README: stop using '= ...' in synopsis to indicate default values.
* IMPROVEMENT: in deploy.bat, change label initials to lowercase to
               distinguish labels from functions.
* IMRPOVEMENT: add more prompts to deploy.bat.

diff --git a/bin/jgcommitnumber b/bin/jgcommitnumber
--- a/bin/jgcommitnumber
+++ b/bin/jgcommitnumber
@@ -1,5 +1,30 @@
 #!/bin/bash
-commitmsg=`git log -1 --pretty=format:"%H"`
-cliped=${commitmsg: 0: ${1:-8}}
-echo "${cliped}"
+
+OPTIND=1
+
+while getopts "h?" opt; do
+    case "$opt" in
+        h|\?)
+            echo -e "\nCommit number"
+            echo -e "Usage:"
+            echo -e "jgcommitnumber [<n>]\n"
+            echo -e "Display and copy the first <n> digits of commit number."
+            echo -e "<n> ranges from 1 to 40, default 8."
+            exit 0
+            ;;
+    esac
+done
+
+shift $((OPTIND-1))
+
+[[ "${1:-}" = "--" ]] && shift
+
+fullhash=`git log -1 --format="%H"`
+length=${1:-8}
+if ! [[ $length =~ ^[0-9]+$ ]]; then
+    echo -e "Invalid argument: not a integer."
+    exit 1
+fi
+cliped=${fullhash: 0: $length}
+git log -1 --abbrev=$length --format="%h %s"
 echo -n "${cliped}" | clip
