Add folder empty check in jgmakesomediff

diff --git a/bin/jgmakesomediff b/bin/jgmakesomediff
--- a/bin/jgmakesomediff
+++ b/bin/jgmakesomediff
@@ -26,6 +26,10 @@ revMod=""
 [[ "${2:-}" ]] && revMod=$2
 
 mkdir -p $outDir/$origDir/ $outDir/$modDir/
+if [[ `ls -A $outDir/$origDir/` || `ls -A $outDir/$modDir/` ]]; then
+    echo "Error: either $outDir/$origDir or $outDir/$modDir is not empty."
+    exit 1
+fi
 
 diffOrig=`git diff --diff-filter=a --name-only $revOrig $revMod 2>/dev/null`
 for origFile in $diffOrig
